Repository cliffdoyle/wget, pull requests merged in 2025-08, with the labels that each got.

#11 Implement Rate Limiting Feature (#4)
  cmd/download.go
  cmd/rate_limiter.go
  cmd/root.go
  go.mod
Labels: documentation, enhancement

#17 Add README, function comments, and basic test
  README.md
  cmd/download.go
  cmd/download_test.go
  cmd/mirror.go
  cmd/root.go
Labels: documentation

#16 Implement development workflow
  .github/workflows/go.yml
Labels: enhancement
